version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - streamlytics-net

  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    command: gcloud beta emulators pubsub start --project=test-project --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
    networks:
      - streamlytics-net

networks:
  streamlytics-net:
    driver: bridge
